In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

**Creating Arrays**

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [10]:
a = np.array([1, 2, 3, 4, 5, 6])

In [12]:
a[2] = 8

In [14]:
a

array([1, 2, 8, 4, 5, 6])

In [16]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [21]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

**Multidimensional Arrays**

In [24]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
n = np.array([
    [1, 2 ,3],
    [4, 5, 6],
    [7, 8, 9]
])

In [28]:
n[0, 2] = 17

In [30]:
n

array([[ 1,  2, 17],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [35]:
n[1] = [23, 46, 69]

In [36]:
n

array([[ 1,  2, 17],
       [23, 46, 69],
       [ 7,  8,  9]])

In [38]:
n[:, 0] = [9, 18, 27]

In [40]:
n

array([[ 9,  2, 17],
       [18, 46, 69],
       [27,  8,  9]])

**Randomly Generated Arrays**

In [55]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [54]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [62]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

**Element-wise Operations**

In [64]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [75]:
b = (10 + (a * 2)) ** 2 / 100

In [78]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

Comparison Operators

In [81]:
a

array([0, 1, 2, 3, 4])

In [80]:
a >= 2

array([False, False,  True,  True,  True])

In [83]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [82]:
a > b

array([False, False,  True,  True,  True])

In [85]:
a[a > b]

array([2, 3, 4])

Summarizing Operations

In [90]:
a.std()

np.float64(1.4142135623730951)